### PR TITLE
launch: fix fullscreen and showClocks setting

### LINKED ISSUE #3786: [launcher] "show clocks" setting doesn't work
### Affected hardware version

Bangle 2

### Your firmware version

2v25.369

### The bug

Launcher completely ignores the "show clocks" setting. The installed clocks are always listed, no matter whether the setting is enabled or not.

### Installed apps

Tested with launcher 0.21, 0.22 and 0.23 on firmware 2v25, 2v25.366 and 2v25.369.

### PR DESCRIPTION
**Pull request by thyttan**
0.24: Fix fullscreen when fastloading the launcher. (TODO:fix back btn flicker)
      Fix respecting the showClocks setting.

Try it via my app loader: https://thyttan.github.io/BangleApps/?id=launch

closes #3786 and #3785

@gfwilliams because it is a core app.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! This looks great! 

For the flicker, I guess there are some options:

* if when we weren't showing widgets we didn't add a `back` handler but instead just add a setWatch on the button?
* Maybe Bangle.setUI shouldn't display a 'back' widget if there are no widgets currently loaded? 
* It looks like if you defined `WIDGETS.back = {remove:()=>{}};` beforehand when fullscreen then it might stop a redraw? Bit of a hack though! https://github.com/espruino/Espruino/blob/master/libs/js/banglejs/Bangle_setUI_Q3.js#L9-L12

File: apps/launch/app.js [hunk 1]
```diff
@@ -81,8 +84,14 @@
         // cleanup the timeout to not leave anything behind after being removed from ram
         if (lockTimeout) clearTimeout(lockTimeout);
         Bangle.removeListener("lock", lockHandler);
+        // Restore widgets if they were hidden by fullscreen setting
+        if (global.WIDGETS) require("widget_utils").show();
```
Comment (bobrippling) [inline apps/launch/app.js:88]: Do we also need:
```suggestion
        if (global.WIDGETS || settings.fullscreen) require("widget_utils").show();
```

or perhaps:
```suggestion
        if (hiddenWidgets) require("widget_utils").show();
```
(with that bool set when we call widget utils' `hide()`)

Comment (gfwilliams) [reply apps/launch/app.js:88]: I *think* we might be ok: https://github.com/espruino/BangleApps/blob/master/modules/widget_utils.js#L21

But it feels like a good idea to check anyway as otherwise it may force a redraw? Did you mean `if (global.WIDGETS && settings.fullscreen)` instead?

Comment (bobrippling) [reply apps/launch/app.js:88]: Ah no - we're looking at it from different sides. Your side is whether it's safe to call (so I can see why you're thinking `&&` and the `widget._draw` check), mine is if we need to undo our changes, which are either if we've done a `.hide()` from having widgets:

https://github.com/espruino/BangleApps/blob/5dd73bbea83c535568a179d56b7478b7d489885c/apps/launch/app.js#L27-L28

or if we've had the fullscreen setting:

https://github.com/espruino/BangleApps/blob/5dd73bbea83c535568a179d56b7478b7d489885c/apps/launch/app.js#L91-L92

If either of those are true, we need to `.show()`, hence `global.WIDGETS || settings.fullscreen`, right?

Comment (thyttan) [reply apps/launch/app.js:88]: But if there are no widgets, there's no need to update their properties with the `.show()` call - right? There's nothing for `widget-utils` to act on.

Comment (bobrippling) [reply apps/launch/app.js:88]: Yes, but then [the for loop](https://github.com/espruino/BangleApps/blob/ebbe4206e604660571020d712e4abea4d01c6e1a/modules/widget_utils.js#L19-L20) wouldn't be entered in that case so we're ok, still. And we're balancing our [above call to `.hide()`](https://github.com/espruino/BangleApps/blob/5dd73bbea83c535568a179d56b7478b7d489885c/apps/launch/app.js#L27-L28), which I think is as far as this code needs to go, and it can then trust that `widget_utils` will do the right thing

File: apps/launch/app.js [hunk 2]
```diff
@@ -81,8 +84,14 @@
...
       }
     });
+    if (settings.fullscreen) {
+      require("widget_utils").hide();
```
Comment (thyttan) [inline apps/launch/app.js:92]: @bobrippling this makes me think you may be right regarding [L88](https://github.com/espruino/BangleApps/pull/3788/files#r2022414408)

Comment (thyttan) [reply apps/launch/app.js:92]: But we also have this consideration about maybe changing the back-function behaviour: https://github.com/espruino/BangleApps/pull/3788#issuecomment-2765635283

Comment (bobrippling) [reply apps/launch/app.js:92]: That's true, it is a bit of a special case I suppose. Perhaps we try out a few different approaches?

Comment (gfwilliams) [reply apps/launch/app.js:92]: Ok - so in this case the widgets would have been hidden before (if there were any), but because we're using `back` a widget is being added anyway and so we're having to hide them again?

I feel we should probably just fix the `back` issue rather than having these lines in there?

File: apps/launch/app.js (hunk 1 above)
Comment (gfwilliams) [reply apps/launch/app.js:88]: Ahh, right - I see what you mean - but actually we only call `require("widget_utils").hide();` when we're supposed to be in fullscreen mode (line 27 is actually `if (!fullscreen) {..} else if (...WIDGETS) ...`. 

If we're not in fullscreen mode we almost certainly do have widgets but they're not hidden.

**Comment by thyttan** [comment]
Without thinking too much about it - yes I like that solution!

**Comment by thyttan** [comment]
I'm debating in my head if the touch in top left corner should still work though even when the widget is not displayed. But probably not?

**Comment by gfwilliams** [comment]
Yeah, although I wonder whether someone might tap in the launcher and expect to launch the app?

I was considering making setUI use an overlay to display the back button in that case, but it just feels like overkill!

**Comment by thyttan** [comment]
> Yeah, although I wonder whether someone might tap in the launcher and expect to launch the app?

It's such a small area that it shouldn't happen very often. But I'm not sure which way is best.

> I was considering making setUI use an overlay to display the back button in that case, but it just feels like overkill!

Agreed. It could be cool - but probably not worth the overhead?

I'd like it in the context of my messagegui changes - but not if it impacts scrolling drawing performance/input latency.

File: apps/launch/app.js (hunk 1 above)
Comment (bobrippling) [reply apps/launch/app.js:88]: Ah I hadn't spotted the fullscreen check, yeah I'm with you

**Comment by bobrippling** [comment]
I suppose one question would be, for apps without widgets do users regularly use the back button anyway? Or are they more likely to soft-reset to escape? Or are we talking menus?

**Comment by gfwilliams** [comment]
> For messagegui it's E.showScroller and not Bangle.setUI though

Ahh - yes, I looked at that. It seems showScroller calls setUI under the hood :)

Having the overlay definitely would hurt scroll performance, so maybe we forget that for now.

> for apps without widgets do users regularly use the back button anyway? Or are they more likely to soft-reset to escape? Or are we talking menus?

Yes, I think they'd almost certainly use the button. I reckon if the whole screen is being used there's a high likelihood that UI elements might end up being over that top left area anyway - imagine if you have a menu with no title - the top menu item would then be forever half obscured by the back button.

I'll go fix setUI then...

**Comment by gfwilliams** [comment]
Huh, well I did that - and I guess as expected it wasn't that easy! Because when widgets are there but hidden WIDGETS is still defined - so I had to check if the widget bar was there. Fixed now though 453def81645c08e46195ad0627c1b77c8a59ee2a

I've updated the launcher code - does this look ok now? Obv it'll need new firmware but I should probably do a release soon anyway

**Comment by thyttan** [comment]
Nice!

I believe so - didn't test now though

**Comment by gfwilliams** [comment]
Just FYI I added another change which allows the item height to be adjusted independently of the font.
