### PR TITLE
drained: fix not restoring when charge threshold met

### LINKED ISSUE #3625: [Drained] App not restoring settings when passing threshold percentage
### Affected hardware version

Bangle 2

### Your firmware version

2v24

### The bug

The drained application overrides the main clock, and various other settings when the watch battery goes below threshold A, then restores these settings at threshold B. A and B are set via drained app settings.

In my case, this is 5% and 15% respectively.

While the watch does swap to drained at 5%, it fails to then restore at 15%, currently requiring me to manually restore via drained's in-app settings, or rebooting the watch itself.

I've not seen this issue reported elsewhere, so I'm not sure if it's one of my other listed apps below interacting with the app causing a problem.

### Installed apps

alarm (0.49), sched (0.27), clock_info (0.12), cprassist (0.02), files (0.08), fileman (0.03), loadingscreen (0.01), dclock (0.10), ptlaunch (0.15), widbt (0.09), qmsched (0.10), wid_edit (0.05), messages (0.62), oxofocus (0.02), notifyfs (0.12), weather (0.26), spotrem (0.11), dragboard (0.10), widadjust (0.03), about (0.15), widalarm (0.02), themesetter (0.05), 2047pp (0.04), diceroll (0.02), dtlaunch (0.25), poweroff (0.04), a_dndtoggle (0.02), lightswitch (0.10), icons (0.02), timerclk (0.07), acmaze (0.05), rebbleagenda (0.02), score (0.02), widmessages (0.06), autoreset (0.02), widdst (0.06), boot (0.63), setting (0.74), powermanager (0.11), widbatpc (0.19), messageicons (0.08), drained (0.06), setuichange (0.03), fontext (0.03), android (0.38), messagegui (0.81), reply (0.03), popconlaunch (0.05)

### PR DESCRIPTION
**Pull request by bobrippling**
previously the assumption was that the `"changing"` event would be fired periodically when charging.

fixes #3625

### CODE REVIEW

**Comment by bobrippling** [comment]
[App deployed here](https://bobrippling.github.io/BangleApps/?id=drained) for testing

File: apps/drained/app.ts [hunk 1]
```diff
@@ -131,19 +131,15 @@ function drainedRestore() { // "public", to allow users to call
...
 };
 
-if (Bangle.isCharging())
-  checkCharge();
-
-Bangle.on("charging", charging => {
-  if(charging) checkCharge();
-});
+checkCharge();
+drainedInterval = setInterval(checkCharge, interval * 60 * 1000);
```
Comment (thyttan) [inline apps/drained/app.ts:142]: Would it not be better to register and deregister the interval on the "charging" event?

Comment (bobrippling) [reply apps/drained/app.ts]: Great idea! Consider it done

**Comment by thyttan** [comment]
Thanks!
