### PR TITLE
Fix settings altitude calibration saving

### LINKED ISSUE #3814: [Altimeter] Altitude resets itself
### Affected hardware version

Bangle 2

### Your firmware version

2v25

### The Bug
The altitude for where I live is 52m. If I go to Settings>System>Altitude in settings and adjust altitude using "up" button to correct altitude, that works. Then If I load Altimeter app, it shows correct altitude. But when pressing button on side to exit app, it resets it back to what it was before (in my case -47m).

I also tried pressing the "Default" Button in Altitude settings, but that just resets it to the original number.

### Expected Behavior
Altitude settings should persist when closing altitude app.

### Steps to Reproduce

1. Go to Settings>System>Altitude in settings. Adjust altitude offset.
2. Load "Altimeter" app, then press side button to exit. Altitude offset will reset.

### Installed apps

_No response_

### PR DESCRIPTION
**Pull request by bobrippling**
By also saving on reset

Fixes #3814

### CODE REVIEW

File: apps/setting/settings.js [hunk 1]
```diff
@@ -1036,35 +1036,41 @@ function showAltitude() {
...
+      altitudeDone();
       popMenu(systemMenu());
     }},
     /*LANG*/"Pressure (hPa)" : menuPressure,
     /*LANG*/"Altitude (m)" : menuAltitude,
     /*LANG*/"Adjust up" : function() {
       Bangle.buzz(80);
       seaLevelPressure++;
-      Bangle.setOptions({seaLevelPressure:seaLevelPressure});
+      Bangle.setOptions({seaLevelPressure});
```
Comment (thyttan) [inline apps/setting/settings.js:1063]: Is it a typo dropping the key:value pairing?

Comment (bobrippling) [reply apps/setting/settings.js:1063]: Ah this is [shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#property_definitions) - `{ x: x }` is equivalent to `{ x }`

Comment (thyttan) [reply apps/setting/settings.js:1063]: Whoa - trippy!

**Comment by thyttan** [comment]
Looks good to me then! I did not try it though.

**Comment by bobrippling** [comment]
Thanks!
