### PR TITLE
clkinfo: make `CLKINFO_FOCUS` a counter

### LINKED ISSUE #3355: [quicklaunch] Wrongly starts app when swiping clock info
### Affected hardware version

Bangle 2

### Your firmware version

2v21

### Bug

On a clock with 2 (or more?) clock info (like Pebble++ Clock):
1. Select the top right clock info
2. Select the top left clock info
3. Swipe left/right/up/down with the intention to switch the top left clock info will trigger quicklaunch instead.

Based on my tests this only happens on the top left clock info and this only happens if you select the top right clock info prior.

### Steps to reproduce

1. Install a clock with 2 clock info like [Pebble++ Clock](https://banglejs.com/apps/?id=pebblepp)
2. Install [quicklaunch](https://banglejs.com/apps/?id=quicklaunch)
3. In Settings > Apps > Quick Launch, setup a quick action on swipe left, right, up or down
4. Start Pebble++ clock from the main menu
5. Select the top right clock info
6. Select the top left clock info
7. Swipe left, right, up or down
8. The quicklaunch is triggered

This bug seems to happen on every clock with more than 2 clock info (#3347)

### Installed apps

alarm (0.46), widalarm (0.01), sched (0.22), setting (0.68), health (0.28), about (0.14), launch (0.20), boot (0.59), antonclk (0.11), widlock (0.08), widbat (0.12), widbt (0.09), widid (0.03), welcome (0.14), notify (0.13), quicklaunch (0.15), clock_info (0.09), pebblepp (0.05)

### PR DESCRIPTION
**Pull request by bobrippling**
This avoids issues when we have multiple clkinfos visible. The first clkinfo may want to focus itself, but a second clkinfo may then unfocus, deleting the first's effects (i.e. setting `CLKINFO_FOCUS`).

In detail:

`CLKINFO_FOCUS` will be set (to `true`) by the first handler (left hand clkinfo) and then unset (/ `delete`d) by the second handler (right hand clkinfo).

This is done in [the `touchHandler`](https://github.com/espruino/BangleApps/blob/c2ea454a3bc7bfaefbc39a5b376510bb9d7d4ec8/apps/clock_info/lib.js#L313-L324).

This commit makes `CLKINFO_FOCUS` a count.

- When we have a tap on a previous clkinfo (previous as in, earlier in the event handler list), it'll focus itself, `CLKINFO_FOCUS++`
- The later handler comes along, unfocuses itself, `CLKINFO_FOCUS--`
- `CLKINFO_FOCUS` is now `1`, so clkinfo is registered as being focussed still, meaning quicklaunch will work because of:

> https://github.com/espruino/BangleApps/blob/c2ea454a3bc7bfaefbc39a5b376510bb9d7d4ec8/apps/quicklaunch/boot.js#L36-L36

Fixes #3355

### CODE REVIEW

**Comment by thyttan** [comment]
> I think the counter solution seems like a good and relatively simple fix!
> 
> I seem to remember some discussion about removing `Bangle.CLKINFO_FOCUS` altogether in favour of just using `.prependListener` and `.stopEventPropagation`. But since it wouldn't be compatible with older firmwares it was not acted on I think. But I don't remember where.

*https://github.com/espruino/BangleApps/issues/3355#issuecomment-2064710458*

Like I said I think this seems like a good thing to merge. But want to let @gfwilliams chime in as well. I also haven't tried it yet.

**Comment by bobrippling** [comment]
Thanks, I'll tag @glemco too, having done the original `CLKINFO_FOCUS` code :)

**Review by glemco — COMMENTED** [review]
Looks good to me. I probably lost a little bit of touch with this code. What is a use case for having _nested_ focus?
I tested this code initially with something like circlesclock and there, tapping on one clkinfo sets the focus, tapping on another should unfocus (blur) the first and focus the new one (in this case just re-setting the variable to true).
Is blur no longer called before the next focus in this scenario? Can we have two clkinfo concurrently selected?

**Comment by thyttan** [comment]
> Is blur no longer called before the next focus in this scenario?

It's not guaranteed to. It depends on the ordering of the touch handlers. If one is selected and you immediately click the other one it might happen that you `focus` the new and then the previous is `blur`:ed, leaving `Bangle.CLKINFO_FOCUS` `undefined` where it ought to be true.

> Can we have two clkinfo concurrently selected?

No, that doesn't happen afaik.

**Comment by bobrippling** [comment]
Yeah, @thyttan's pretty much summed it up, to add one extra bit - it's less of a nested focus and more that the count prevents one clkinfo from clobbering what another one might set, if one gets focused before the other one's blur handler has run.

I've tested this and it looks to have resolved the bug in `quicklaunch`

File: apps/clock_info/lib.js [hunk 1]
```diff
@@ -298,7 +298,7 @@ exports.addInteractive = function(menu, options) {
   };
   const focus = () => {
     let redraw = true;
-    Bangle.CLKINFO_FOCUS=true;
+    Bangle.CLKINFO_FOCUS = (Bangle.CLKINFO_FOCUS || 0) + 1;
```
Comment (gfwilliams) [inline apps/clock_info/lib.js:301]: Please could we make this just `(0|Bangle.CLKINFO_FOCUS) + 1;`?

It's just a bit more robust (eg if `Bangle.CLKINFO_FOCUS=="1"` the result of running this code is the string `"11"`)

Comment (bobrippling) [reply apps/clock_info/lib.js]: Sure, sorted 👍

**Comment by gfwilliams** [comment]
Thanks! This looks good, however I honestly thought this worked properly at some point!

As @glemco mentioned the idea was that the previous item would be blurred before the next was focussed - but maybe that never actually happened, and I only tested the case where I tapped outside the current clkinfo and then onto the next one, rather than tapping directly on the next :)

**Review by glemco — APPROVED** [review]

**Comment by thyttan** [comment]
OK - thanks everybody!

**Comment by bobrippling** [comment]
Thanks for the reviews and discussion :)
